name: dotnet
on:
    pull_request:
        branches:
        - develop
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Setup dotnet
          uses: actions/setup-dotnet@v5
          with:
            dotnet-version: |
              9.0.x

        - uses: actions/checkout@v5

        - name: restore
          run: dotnet restore src/Presentation/Nop.Web/Nop.Web.csproj

        - name: build
          run: dotnet build --configuration Debug src/Presentation/Nop.Web/Nop.Web.csproj

        - name: Run tests (TRX output)
          run: dotnet test --logger:"trx;LogFilePrefix=testResults" --results-directory ./TestResults src/Tests/Nop.Tests/Nop.Tests.csproj

        # Upload raw TRX
        - name: Upload TRX report
          uses: actions/upload-artifact@v4
          with:
            name: test-results-trx
            path: '**/TestResults/*.trx'

        - name: publish
          run: dotnet publish --configuration Release src/Presentation/Nop.Web/Nop.Web.csproj --output published

        # ✅ Zip the published output
        - name: Zip artifact
          run: zip -r ${{ github.event.repository.name }}-${{ github.run_number }}.zip published

        # ✅ Upload artifact to GitHub Actions
        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: ${{ github.event.repository.name }}-${{ github.run_number }}
            path: ${{ github.event.repository.name }}-${{ github.run_number }}.zip
